# Generated by Django 3.2 on 2021-04-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_auto_20210416_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='overall_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='rating_count',
            field=models.FloatField(null=True),
        ),
    ]
