# Generated by Django 3.2 on 2021-04-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_auto_20210421_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='overall_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='rating_count',
            field=models.FloatField(default=0),
        ),
    ]
